[package]
name = "mancala-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
heapless = "0.9.1"
thiserror = "2.0.14"

[dev-dependencies]
criterion = "0.7.0"
rstest = "0.26.1"

# [[bin]]
# name = "precompute_walk"
# path = "bin/precompute_walk.rs"
